language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - 8.2.1
deploy:
  skip-cleanup: true
  provider: script
  script: bash ./scripts/deploy.sh
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
