language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - 8.2.1
before-script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - npm install
scripts:
  - bash ./scripts/deploy.sh
deploy:
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
